Repository fmd-project-team/FMD, pull requests merged in 2019-12, with the labels that each got.

#656 Fixed can't download some chapters [BacaManga]; Added support for web…
  lua/modules/Madara.lua
  lua/modules/MangaShiro.lua
Labels: Fixed, Site Added, Site Changed, Site Request

#659 Website changed domain [Toonkor]
  lua/modules/Toonkor.lua
Labels: Fixed, Site Changed

#663 Updated image extraction [BacaManga]
  lua/modules/MangaShiro.lua
Labels: Fixed, Site Changed

#670 add and fixed
  lua/modules/HeavenManga.lua
  lua/modules/NewToki.lua
  lua/modules/RawDevart.lua
  lua/modules/myReaderMangaCMS.lua
Labels: Fixed, Lua, Site Added

#675 Fixed can't download some images [HentaiFox]
  lua/modules/HentaiFox.lua
Labels: Fixed, Site Changed

#681 Move template to Genkan [ZeroScans]
  lua/modules/Madara.lua
  lua/modules/ZeroScans.lua
Labels: Fixed, Site Changed

#694 fixed update modules
  mangadownloader/forms/frmLuaModulesUpdater.pas
Labels: Bug, Fixed, Pascal
