Repository fmd-project-team/FMD, pull requests merged in 2019-11, with the labels that each got.

#601 Add support for website [ManhuaID]
  lua/modules/ManhuaID.lua
Labels: Site Added, Site Request

#602 Add support for website [Mangakyo]
  lua/modules/MangaShiro.lua
Labels: Site Added, Site Request

#611 Fixed can't get manga list [NManhwa]
  lua/modules/Madara.lua
Labels: Fixed, Site Changed

#613 Fixed getting chapter list [PlotTwistNoFansub]
  lua/modules/Madara.lua
Labels: Fixed, Site Changed

#616 Update Madara.lua
  lua/modules/Madara.lua
Labels: Site Added, Site Request

#628 Fixed image download [BacaManga, Kiryuu]
  lua/modules/MangaShiro.lua
Labels: Fixed, Lua, Site Changed

#632 Fixed image download [BacaManga]
  lua/modules/MangaShiro.lua
Labels: Fixed, Site Changed

#633 Update Madara.lua
  lua/modules/Madara.lua
Labels: Site Added, Site Request

#634 Update Madara.lua
  lua/modules/Madara.lua
Labels: Fixed

#639 Fixed image download [BacaManga]
  lua/modules/MangaShiro.lua
Labels: Fixed, Site Changed

#638 Fixed image download and update manga list [HentaiFox]
  lua/modules/HentaiFox.lua
Labels: Fixed, Site Changed

#644 Fixed some titles can't be downloaded and title detection [Manhwa18]
  lua/modules/Lhscans.lua
Labels: Fixed, Site Changed

#645 Added more filter for spam and ad images [Kiryuu]
  lua/modules/MangaShiro.lua
Labels: Fixed, Site Changed

#649 Fixed getting thumbnail images instead of actual images [HentaiFox]
  lua/modules/HentaiFox.lua
Labels: Fixed, Lua

#648 Fixed image download [Lhscans]
  lua/modules/Lhscans.lua
Labels: Fixed, Lua, Site Changed

#652 Adapted new changes [BacaManga]
  lua/modules/MangaShiro.lua
Labels: Fixed, Site Changed
