Repository fmd-project-team/FMD, pull requests merged in 2019-09, with the labels that each got.

#471 Fix chapter download [MangaShiro][MangaYosh][DoujinYosh]
  lua/modules/Madara.lua
  lua/modules/MangaShiro.lua
Labels: Site Changed

#473 Update Indonesian localization
  languages/fmd.id_ID.po
Labels: Localization

#474 Updated FR translation for new items
  languages/fmd.fr.po
Labels: Localization

#476 [HeavenManga] and [HolyManga] change url
  lua/modules/HeavenManga.lua
Labels: Lua, Site Changed

#475 remove [mangalike] and add [mangakomi]
  lua/modules/Madara.lua
Labels: Lua, Site Changed

#488 Website changed URL [UnionMangas]
  lua/modules/UnionMangas.lua
Labels: Fixed, Site Changed

#487 Add support for website [WoweScans]
  lua/modules/WoweScans.lua
Labels: Fixed, Site Changed

#492 fix chapter download #491
  lua/modules/Lhscans.lua
Labels: Fixed, Lua, Site Changed

#495 Update Indonesian localization
  languages/fmd.id_ID.po
Labels: Localization

#496 Add support for website [WakaScan]
  lua/modules/Madara.lua
Labels: Site Added, Site Request

#502 add website [Manhwa18] #499 and fix chapter download
  lua/modules/Lhscans.lua
Labels: Fixed, Site Added, Site Changed, Site Request

#504 [HeavenManga] Change Url #500
  lua/modules/HeavenManga.lua
Labels: Fixed, Lua, Site Changed

#505 Can't get manga list [KlikManga, MangaPus, Toonily]
  lua/modules/Madara.lua
  lua/modules/MangaShiro.lua
Labels: Fixed, Site Changed

#508 Update Madara.lua
  lua/modules/Madara.lua
Labels: Lua, Site Changed

#510 Update Madara.lua
  lua/modules/Madara.lua
Labels: Fixed, Lua, Site Changed

#523 Website changed domain [MangaYosh, DoujinYosh]
  lua/modules/Madara.lua
Labels: Fixed, Site Changed
