Repository fmd-project-team/FMD, pull requests merged in 2020-07, with the labels that each got.

#1063 Update HeavenManga.lua
  lua/modules/HeavenManga.lua
  lua/modules/Madara.lua
Labels: Site Changed

#1064 Update HeavenManga.lua
  lua/modules/HeavenManga.lua
Labels: Site Changed

#1078 Fix Website Changes
  lua/modules/MangaShiro.lua
Labels: Site Changed

#1079 Update Madara.lua
  lua/modules/Madara.lua
Labels: Site Added, Site Request

#1082 Fixed HeavenManga
  lua/modules/HeavenManga.lua
  lua/modules/Madara.lua
Labels: Lua, Site Added, Site Changed

#1087 Update Madara.lua
  lua/modules/Madara.lua
Labels: Lua, Site Added, Site Request

#1092 Update Madara.lua
  lua/modules/Madara.lua
Labels: Site Added, Site Request
