Repository fmd-project-team/FMD, pull requests merged in 2020-01, with the labels that each got.

#711 Change Mangadex domain
  lua/modules/MangaDex.lua
Labels: Site Changed

#731 Mangadex change domain back
  lua/modules/MangaDex.lua
Labels: Site Changed

#735 Update MangaDex.lua
  lua/modules/MangaDex.lua
Labels: Site Changed

#726 Update TMOHentai.lua
  lua/modules/TMOHentai.lua
Labels: Site Changed

#586 update name. ChampionScans -> ProjectTime
  lua/modules/ComiCake.lua
Labels: Decision Pending, Lua, Site Changed

#738 Added support for Weibo Manhua
  lua/modules/WeiboManhua.lua
Labels: Lua, Site Added, Site Request
