Repository fmd-project-team/FMD, pull requests merged in 2020-03, with the labels that each got.

#853 Added EarlyManga.website to Madara
  lua/modules/Madara.lua
Labels: Site Added

#870 Added 1stKissManga to Madara
  lua/modules/Madara.lua
Labels: Site Added

#871 Update MintMangaRU.lua
  lua/modules/MintMangaRU.lua
Labels: Site Changed

#875 HeavenManga & HolyManga
  lua/modules/HeavenManga.lua
Labels: Fixed, Lua
